
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'budget_manager'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'budget_manager'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"

# When partial parsing is enabled, dbt will use that internal manifest to determine which files have been changed (if any) since it last parsed the project.
# Then, it will only parse the changed files, or files related to those changes.
flags:
  partial_parse: false # Turned off because it often misses to execute the accurate version of my changed files.

data_tests:
  +store_failures: true
  +schema: dbt_test_error

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  budget_manager:
    02_stg:
      +schema: staging
    03_dwh:
      +schema: warehouse

# Configuring snapshots
snapshots:
  budget_manager:
  # +schema: warehouse  # Commented out. I have to use it in each individual snap config, because here it's overwriten by the profiles.yml file.
    +database: "{{ env_var('POSTGRES_DB') }}"
    +strategy: check  # no timestamp strategy because using last_edited_time is risky (can change even when copy pages in Notion)

  # Dynamically choose the column/expression based on the injected variable.
  # last_edited_time is needed only for the initial load, to set scd2_valid_from = 1990-01-01.
    +updated_at: "{{ 'last_edited_time' if var('execution_input', {}).get('is_initial_load', false) else 'current_timestamp' }}"
  # +updated_at: last_edited_time  # Needed only for the initial load, to set scd2_valid_from = 1990-01-01.

    +snapshot_meta_column_names: { 'dbt_scd_id'     : 'dk'              ,
                                   'dbt_updated_at' : 'scd2_updated_at' ,
                                   'dbt_valid_from' : 'scd2_valid_from' ,
                                   'dbt_valid_to'   : 'scd2_valid_to'
                                  }
    +dbt_valid_to_current: "CAST('9999-12-31 00:00:00' AS TIMESTAMP)"
    +hard_deletes: invalidate

