budget_manager:
  outputs:
    dev:
      type: postgres
      host: budget-db
      schema: staging
      dbname: "{{ env_var('POSTGRES_DB') }}"
      user:   "{{ env_var('POSTGRES_USER') }}"
      pass:   "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      threads: 1
  target: dev
